Revert "CherryPicked: [cnv-4.19] CherryPicked: [4.21] Fix _sc_name_for_storage_api" (#5488)
Reverts RedHatQE/openshift-virtualization-tests#5438

breaks gating lanes `failed on setup with "TypeError:
get_default_storage_class() got an unexpected keyword argument
'client'"`

Signed-off-by: vsibirsk <vsibirsk@redhat.com>